# Generated by Django 5.2.7 on 2025-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='Dirección temporal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='credit_card', max_length=50),
        ),
    ]
